Add class 2 katas solution
Fictizia/Curso-de-JavaScript-avanzado-para-desarrolladores_ed5 pull request #24
Opened 2020-10-04 09:03 UTC by Sonia-SV

Sonia's answers to class 2 exercise

2020-10-04 18:52 UTC, totegsito requested changes
Me han flipado tus soluciones 😬  Pero les he visto una pega, abusas del break, que es algo que se debería usar sólo como ultimísimo ultimísimo recurso ya que se considera una mala práctica fuera de los switch 😅

Échale un ojo a las anotaciones y si te surje cualquier duda me cuentas 😄

2020-10-04 18:52 UTC, totegsito commented on alumnos/ssv/Clase 2/ejercicio2.js
> +    return true;
Aquí puedes devolver directamente la condición del if:

```javascript
return num % 2 === 0
```

2020-10-04 18:52 UTC, totegsito commented on alumnos/ssv/Clase 2/ejercicio3.js
> +const removeAccents = (str) => {
Bien visto, pero para este caso de verdad que no hacía falta 😅

2020-10-04 18:52 UTC, totegsito commented on alumnos/ssv/Clase 2/ejercicio4.js
> +      break;
Esto no me gusta nada 😅  El uso de break fuera de los switch está considerado una mala práctica. En vez de esto, puedes hacer `return i` que también corta el bucle 😄  Aun así, bien visto lo de ir de atrás hacia delante con el array 🥳

2020-10-04 18:52 UTC, totegsito commented on alumnos/ssv/Clase 2/ejercicio3.js
> +  }
🆒

2020-10-04 18:52 UTC, totegsito commented on alumnos/ssv/Clase 2/ejercicio5.js
> +      break;
Genial la solución, sólo recuerda que cada vez que usamos un break fuera de un switch muere un gatito 😿

2020-10-04 18:52 UTC, totegsito commented on alumnos/ssv/Clase 2/ejercicio6.js
> +    { day: "domingo", hate: number === 666 || number === -666 },
Este era un caso muy claro de switch 😅  No digo que tu solución no sea buena, pero si es verdad que un ciclo for siempre será menos óptima que usar condiciones como switch o incluso if anidados 😅

Aun así, muy guay que hayas tirado por objetos 😄

2020-10-04 18:52 UTC, totegsito commented on alumnos/ssv/Clase 2/ejercicio1.js
> +        break;
![terrorism](https://media.giphy.com/media/l0HlCjhxMSf6OEX96/giphy.gif)

2020-10-05 10:16 UTC, Sonia-SV commented on alumnos/ssv/Clase 2/ejercicio1.js
> +          break;
Sin este break me entra en bucle porque empieza a comprobarse el último número consigo mismo y no sé cómo solucionarlo sin mirar el método bubble en stack overflow.

2020-10-05 10:32 UTC, merged