Add day 3 exercises
Fictizia/Curso-de-JavaScript-avanzado-para-desarrolladores_ed5 pull request #32
Opened 2020-10-05 21:27 UTC by Sonia-SV

2020-10-11 13:33 UTC, totegsito requested changes
Te falta un detallito en el de los números ingleses y ya lo tendrías 😄 

Además, te pediría si por favor podrías borrar el .DS_Store de tu carpeta, lo acabas de subir😅

2020-10-11 13:33 UTC, totegsito commented on alumnos/ssv/Clase 3/ejercicio7.js
> +console.assert(camelize('Hola a todos que tal') === 'holaATodosQueTal');
Genial! 🥇

2020-10-11 13:33 UTC, totegsito commented on alumnos/ssv/Clase 3/ejercicio8.js
> +  const lastNum = num.slice(-1);
Lo que recibe es número, no string 😅

2020-10-11 21:50 UTC, Sonia-SV commented on alumnos/ssv/Clase 3/ejercicio8.js
> +  const lastNum = num.slice(-1);
Recibe un string porque la función getSufix es invocada desde englishNumber y ya le pasa el valor como string. Le voy a cambiar el nombre al parámetro de getSufix para que no cree confusión

2020-10-11 21:52 UTC, Sonia-SV commented on alumnos/ssv/Clase 3/ejercicio8.js
> +  const lastNum = num.slice(-1);
Como ya recibía el número desde englishNumber como un string me parecía repetitivo, pero se lo cambio

2020-10-12 17:55 UTC, totegsito approved these changes
Genial!

2020-10-12 17:55 UTC, merged