Ejercicios clase 3
Fictizia/Curso-de-JavaScript-avanzado-para-desarrolladores_ed5 pull request #39
Opened 2020-10-08 14:22 UTC by VeroMoreno

¡Bravo ahora si!, aquí solo van los ejercicios de la clase 3!

2020-10-11 14:03 UTC, totegsito requested changes
Un detalle pequeño en el ejercicio de la pandemia y ya lo tendrías! 👏

2020-10-11 14:03 UTC, totegsito commented on alumnos/vmf/clase3_ejercicios/9.pandemic.js
> +   return resultado = infected * 100 / totalCities;
Te faltaría sólo el caso de 'XXXXX' 😄

2020-10-18 11:51 UTC, totegsito commented on alumnos/vmf/clase3_ejercicios/9.pandemic.js
> +            var find = "0"
Qué hacemos con los var en estas tierras? 

![](https://media.giphy.com/media/GiV7AxwduuKac/giphy.gif)

2020-10-18 11:51 UTC, totegsito requested changes
Todo bien salvo lo del `var`, que realmente no lo necesitas aquí 😅

2020-10-18 17:09 UTC, VeroMoreno commented
mierda! se me coló el var!!! YA ESTA OUTEN!

2020-10-25 16:18 UTC, totegsito approved these changes
💪

2020-10-25 16:19 UTC, merged