ejercicios clase 4
Fictizia/Curso-de-JavaScript-avanzado-para-desarrolladores_ed5 pull request #42
Opened 2020-10-11 08:46 UTC by ifuenteromero

Ejercicios clase 4

2020-10-11 14:35 UTC, totegsito requested changes
Muy buen curro! En el del carrito te falta un detalle y ya lo tendrías 👏

2020-10-11 14:35 UTC, totegsito commented on alumnos/ifr/clase4.js
> +        return this.productos.reduce(({ precio: precioA, unidades: unidadesA }, { precio: precioB, unidades: unidadesB }) => precioA * unidadesA + precioB * unidadesB )
Esto te está funcionando porque en la prueba hay dos elementos sólo, si metes uno más va a devolver NaN ya que intentará acceder a las propiedades `precio` y `unidades` del `precioTotal` que calcules en la primera iteración 😅

2020-10-11 14:35 UTC, totegsito commented on alumnos/ifr/clase4.js
> +		return `Creo que podría gustarte el libro '${nombre}' de '${autor}'`;
Genial! 👏

2020-10-12 09:57 UTC, ifuenteromero commented on alumnos/ifr/clase4.js
> +        return this.productos.reduce(({ precio: precioA, unidades: unidadesA }, { precio: precioB, unidades: unidadesB }) => precioA * unidadesA + precioB * unidadesB )
Gracias por tus comentarios. He corregido el reduce

2020-10-12 17:54 UTC, totegsito approved these changes
Muy bien hecho! :-D

2020-10-12 17:54 UTC, totegsito commented on alumnos/ifr/clase4.js
> +        return this.productos.reduce((precioTotal, { unidades, precio }) => precioTotal + unidades * precio, 0 )
Perfecto!

2020-10-12 17:54 UTC, merged