crr/exercises-class-5
Fictizia/Curso-de-JavaScript-avanzado-para-desarrolladores_ed5 pull request #48
Opened 2020-10-12 10:51 UTC by crod2

2020-10-12 18:21 UTC, totegsito requested changes
Un detalle ínfimo y ya estaría 😄

2020-10-12 18:21 UTC, totegsito commented on alumnos/cr/class-5/exercises-two-and-three.js
> +          libros = (...libros, ...librosPrestados)
Esto tendrían que ser corchetes 😅

2020-10-12 18:21 UTC, totegsito commented on alumnos/cr/class-5/exercise-one.js
> +}
Genial!

2020-10-12 21:10 UTC, crod2 commented on alumnos/cr/class-5/exercises-two-and-three.js
> +          libros = (...libros, ...librosPrestados)
Ay jo, claro, ¡muchas gracias!

2020-10-18 12:05 UTC, totegsito approved these changes
🆒

2020-10-18 12:06 UTC, merged