Ejercicios clase 5
Fictizia/Curso-de-JavaScript-avanzado-para-desarrolladores_ed5 pull request #56
Opened 2020-10-15 11:43 UTC by VeroMoreno

Lo dicho Fran. Si me recomiendas más ejercicios para hacer con
map - forEach - filter & reduce que veas que me pueden hacer pensar más perfecto.
Gracias!

2020-10-18 12:41 UTC, totegsito requested changes
Buen trabajo Vero, pero te falta un detallito del enunciado. Dale una vuelta y si no lo ves me dices y te indico 😬

2020-10-18 12:41 UTC, totegsito commented on alumnos/vmf/clase5_ejercicios/2.prestarLibrosAlVecino.js
> +    prestamo(flag) {
Aquí lo que estás haciendo es reemplazar la propiedad prestamo que has declarado antes 😬  Te faltaría la parte de que sea una propiedad que cuando se modifica provoque que ocurran cosas por detrás 😅

2020-10-18 12:41 UTC, totegsito commented on alumnos/vmf/clase5_ejercicios/3.devolucionDeLibrosALaEstanteria.js
> +    prestamo(flag) {
Idem del anterior comentario 😄

2020-10-22 06:44 UTC, VeroMoreno commented
Ya lo tienes Fran!, perdona porque como ves no me llevo muy bien con los getters y setters, tuve que mirarme la clase 4 para entender mejor como funcionaba y ahora entendí lo de "propiedad cuando se modifica". Gracias!

2020-10-25 16:23 UTC, totegsito approved these changes
🆒

2020-10-25 16:23 UTC, merged